export const BOTAO_CLICADO_REQUEST = 'BOTAO_CLICADO_REQUEST';
export const BOTAO_CLICADO_SUCCESS = 'BOTAO_CLICADO_SUCCESS';
export const BOTAO_CLICADO_FAILURE = 'BOTAO_CLICADO_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const UPDATE_REQUEST = 'UPDATE_REQUEST';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
export const UPDATE_FAILURE = 'UPDATE_FAILURE';

export const REWARD_REQUEST = 'REWARD_REQUEST';
export const REWARD_SUCCESS = 'REWARD_SUCCESS';
export const REWARD_FAILURE = 'REGISTER_FAILURE';

export const ITEM_REQUEST = 'ITEM_REQUEST';
export const ITEM_SUCCESS = 'ITEM_SUCCESS';
export const ITEM_FAILURE = 'REGISTER_FAILURE';

export const ENERGY_RECALL = 'ENERGY_RECALL';
export const ENERGY_RECALL2 = 'ENERGY_RECALL2';
export const CHANGEITEM_REQUEST = 'CHANGEITEM_REQUEST';

export const PAYQUEST_REQUEST = 'PAYQUEST_REQUEST';
export const PAYQUEST_SUCCESS = 'PAYQUEST_SUCCESS';

export const SHOGUNQUEST_REQUEST = 'SHOGUNQUEST_REQUEST';
export const SHOGUNQUEST_SUCCESS = 'SHOGUNQUEST_SUCCESS';

export const GOLDCHANGE_REQUEST = 'GOLDCHANGE_REQUEST';
export const GOLDCHANGE_SUCCESS = 'GOLDCHANGE_SUCCESS';

export const REQUEST_FRAGMENTS = 'REQUEST_FRAGMENTS';
export const UPDATE_FRAGMENTS = 'UPDATE_FRAGMENTS';

export const CREATE_ITEM_REQUEST = 'CREATE_ITEM_REQUEST';
export const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS';
export const CREATE_ITEM_FAILURE = 'CREATE_ITEM_FAILURE';

export const PAYFRAGMENTS_REQUEST = 'PAYFRAGMENTS_REQUEST';
export const PAYFRAGMENTS_SUCCESS = 'PAYFRAGMENTS_SUCCESS';
